/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/panel/component/Button.vue')['default']
    Dialog: typeof import('./src/panel/component/Dialog.vue')['default']
    Divider: typeof import('./src/panel/component/Divider.vue')['default']
    Highlighter: typeof import('./src/panel/component/Highlighter.vue')['default']
    Item: typeof import('./src/panel/component/Item.vue')['default']
    JsonEditor: typeof import('./src/panel/component/JsonEditor.vue')['default']
    Popup: typeof import('./src/panel/component/Popup.vue')['default']
    RadioButtonGroup: typeof import('./src/panel/component/RadioButtonGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/panel/component/SearchBar.vue')['default']
    Selector: typeof import('./src/panel/component/Selector.vue')['default']
    Toggle: typeof import('./src/panel/component/Toggle.vue')['default']
  }
}
